default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: jothis
  password: jana
  host: localhost
  port: 5433

development:
  <<: *default
  database: property-finder

test:
  <<: *default
  database: test1

production:
  <<: *default
  database: production1
